import { STORAGE_KEY, freshState, searchNotes, projectProgress, statuses, isValidState } from './model.js';
const $ = (q) => document.querySelector(q);
const icons = {
 overview: '<rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/>',
 projects:'<path d="M3 7a2 2 0 0 1 2-2h5l2 2h7a2 2 0 0 1 2 2v10H3Z"/>',
 knowledge:'<path d="M12 5c-3-2-6-2-9-1v15c3-1 6-1 9 1 3-2 6-2 9-1V4c-3-1-6-1-9 1Zm0 0v15"/>',
 tasks:'<rect x="4" y="4" width="16" height="17" rx="3"/><path d="M9 3h6M8 12l2 2 6-6M8 18h8"/>',
 search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/>', plus:'<path d="M12 5v14M5 12h14"/>', arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>', down:'<path d="M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4"/>', check:'<path d="m5 12 4 4L19 6"/>', clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>', sparkle:'<path d="m12 3 3 6 6 3-6 3-3 6-3-6-6-3 6-3Z"/>'
};
const ico = (name) => `<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]||icons.sparkle}</svg>`;
const esc = (s) => String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=freshState(), storageError=false;
try { const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null'); if(isValidState(saved)) state=saved; } catch { storageError=true; }
state.requests ||= [];
let view='overview', selectedProject='p1', query='', taskFilter='全部', selectedNote=null;
function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));return true;}catch{storageError=true;toast('浏览器无法保存。请导出备份，避免丢失更改。');return false;}}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');setTimeout(()=>$('#toast').classList.remove('visible'),3500);}
const project = id => state.projects.find(p=>p.id===id);
function nav(){return `<aside class="sidebar"><a class="brand" href="#overview"><span class="brand-mark">${ico('sparkle')}</span><span>GPT-DOT-WORK</span></a><div class="workspace-select"><span class="avatar">我</span><div><strong>我的工作空间</strong><small>让想法有迹可循</small></div><span class="chevron">⌄</span></div><div class="nav-label">工作空间</div><nav>${[['overview','总览'],['projects','项目'],['knowledge','知识库'],['tasks','任务']].map(([key,name])=>`<a href="#${key}" class="nav-item ${view===key?'active':''}" ${view===key?'aria-current="page"':''}>${ico(key)}<span>${name}</span>${key==='tasks'?`<em>${state.tasks.filter(t=>t.status!=='已完成').length}</em>`:''}</a>`).join('')}</nav><div class="sidebar-projects"><div class="nav-label">置顶项目</div>${state.projects.map(p=>`<button class="project-link" data-project="${p.id}"><i class="dot ${p.color}"></i>${p.name}</button>`).join('')}</div><div class="sidebar-bottom"><div class="local-label"><span class="status-dot"></span>本地演示空间</div><p>数据保存在当前浏览器<br>未连接聊天、AI 或执行器</p><button class="export-button" data-action="export">${ico('down')}导出本地数据</button><div class="profile"><span class="avatar small">我</span><div><strong>探索者</strong><small>独立项目 · 非官方</small></div></div></div></aside>`;}
function header(){return `<header class="topbar"><div class="breadcrumb">工作空间 <span>/</span> <strong>${{overview:'总览',projects:'项目',knowledge:'知识库',tasks:'任务'}[view]}</strong></div><div class="topbar-right"><span class="demo-badge">交互原型</span><span class="avatar small">我</span></div></header>`;}
function taskRow(t){return `<div class="task-row"><button class="task-check ${t.status==='已完成'?'checked':''}" data-toggle-task="${t.id}" aria-label="${t.status==='已完成'?'重新打开':'完成'}：${esc(t.title)}">${t.status==='已完成'?ico('check'):''}</button><div class="task-main"><strong class="${t.status==='已完成'?'strike':''}">${esc(t.title)}</strong><small>${esc(project(t.projectId)?.name)} <span>·</span> ${esc(t.due)}</small></div>${t.priority==='优先'?'<span class="priority">优先</span>':''}<select class="status-select" aria-label="${esc(t.title)}状态" data-task-status="${t.id}">${statuses.map(s=>`<option ${s===t.status?'selected':''}>${s}</option>`).join('')}</select></div>`;}
function projectCard(p){let progress=projectProgress(state,p.id);return `<button class="project-card" data-project="${p.id}"><div class="card-top"><span class="project-icon ${p.color}">${p.icon}</span><span class="tag">${p.category}</span><span class="card-arrow">↗</span></div><h3>${p.name}</h3><p>${p.description}</p><div class="progress-meta"><span>${p.stage}</span><span>${progress}%</span></div><div class="progress-track"><div style="width:${progress}%" class="${p.color}"></div></div><div class="card-bottom"><span>${state.notes.filter(n=>n.projectId===p.id).length} 篇笔记</span><span>${state.tasks.filter(t=>t.projectId===p.id&&t.status!=='已完成').length} 项待办 ${ico('arrow')}</span></div></button>`;}
function noteCard(n){return `<button class="note-card" data-note="${n.id}"><div class="note-meta"><span class="note-type">${ico('knowledge')}${esc(n.type)}</span><span>${esc(n.updated.slice(0,10))}</span></div><h3>${esc(n.title)}</h3><p>${esc(n.body.replace(/\n/g,' '))}</p><div class="note-tags">${n.tags.map(t=>`<span># ${esc(t)}</span>`).join('')}</div><div class="note-project"><i class="dot ${project(n.projectId)?.color||'blue'}"></i>${esc(project(n.projectId)?.name)}</div></button>`;}
function overview(){const open=state.tasks.filter(t=>t.status!=='已完成'), decisions=state.decisions.filter(d=>!d.resolved);return `<section class="welcome"><div><div class="eyebrow">YOUR PERSONAL WORKSPACE</div><h1>给想法一个落脚的地方<span>。</span></h1><p>把知识连起来，把重要的事慢慢做好。</p></div><button class="button primary" data-action="new-note">${ico('plus')}记录想法</button></section><section class="summary-grid"><div><span class="summary-icon blue">${ico('projects')}</span><p>进行中的项目<strong>${state.projects.length}<small>个正在生长的方向</small></strong></p></div><div><span class="summary-icon purple">${ico('knowledge')}</span><p>积累的知识<strong>${state.notes.length}<small>条想法，随时可回顾</small></strong></p></div><div><span class="summary-icon orange">${ico('tasks')}</span><p>待推进的任务<strong>${open.length}<small>专注下一步行动</small></strong></p></div></section><section><div class="section-heading"><h2>正在推进 <span>把注意力留给重要的事</span></h2><a href="#projects">查看全部 ${ico('arrow')}</a></div><div class="project-grid">${state.projects.map(projectCard).join('')}</div></section><div class="two-column"><section class="panel"><div class="section-heading"><h2>接下来做什么 <span class="count">${open.length}</span></h2><a href="#tasks">全部任务 ${ico('arrow')}</a></div>${open.slice(0,3).map(taskRow).join('')||'<p class="empty">暂时没有待办，享受一点留白。</p>'}</section><section class="decision-panel"><div class="section-heading"><h2>${ico('sparkle')} 等你决定</h2><span class="count">${decisions.length}</span></div>${decisions.map(d=>`<div class="decision"><small>${esc(project(d.projectId)?.name)}</small><h3>${esc(d.title)}</h3><p>${esc(d.detail)}</p><button data-decision="${d.id}">标记已决定 ${ico('arrow')}</button></div>`).join('')||'<p class="empty">所有决定都已处理。</p>'}</section></div><section><div class="section-heading"><h2>最近留下的想法 <span>为下一次灵感铺路</span></h2><a href="#knowledge">打开知识库 ${ico('arrow')}</a></div><div class="note-grid">${[...state.notes].sort((a,b)=>b.updated.localeCompare(a.updated)).slice(0,3).map(noteCard).join('')}</div></section>`;}
function projects(){let p=project(selectedProject)||state.projects[0];return `<div class="page-heading"><div><div class="eyebrow">PROJECTS</div><h1>让每个方向，向前一步。</h1><p>计划、知识和行动，在这里汇合。</p></div></div><div class="project-grid">${state.projects.map(projectCard).join('')}</div><section class="project-detail panel"><div class="detail-heading"><span class="project-icon ${p.color}">${p.icon}</span><div><small>${p.category} / ${p.stage}</small><h2>${p.name}</h2></div><span class="tag">${projectProgress(state,p.id)}% 已完成</span></div><div class="plan-box"><span>当前计划</span><p>${esc(p.plan)}</p></div><div class="section-heading"><h2>下一步行动</h2><button class="text-button" data-action="new-task">+ 添加任务</button></div>${state.tasks.filter(t=>t.projectId===p.id).map(taskRow).join('')}<div class="section-heading"><h2>相关知识</h2><button class="text-button" data-action="new-note">+ 写一条笔记</button></div><div class="note-grid">${state.notes.filter(n=>n.projectId===p.id).map(noteCard).join('')||'<p class="empty">还没有笔记，记录第一条想法吧。</p>'}</div></section>`;}
function knowledge(){let notes=searchNotes(state.notes,query);return `<div class="page-heading"><div><div class="eyebrow">KNOWLEDGE GARDEN</div><h1>知识在连接中生长。</h1><p>收下灵感，也留下自己的理解。</p></div><button class="button primary" data-action="new-note">${ico('plus')}新建笔记</button></div><div class="knowledge-toolbar"><label class="search">${ico('search')}<input id="knowledge-search" placeholder="搜索标题、内容或标签…" value="${esc(query)}" aria-label="搜索知识库"><kbd>⌘ K</kbd></label><span>${notes.length} 篇笔记</span></div><div class="note-grid knowledge-grid">${notes.map(noteCard).join('')||'<div class="empty panel">没有找到相关笔记。试试其他关键词。</div>'}</div>`;}
const queueLabels={draft:'草稿',pending:'排队中',running:'执行中',blocked:'受阻',needs_approval:'等待授权',completed:'已完成',failed:'失败',cancelled:'已取消'};
function tasks(){return `<div class="page-heading"><div><div class="eyebrow">FOCUS & ACTION</div><h1>从一个小行动开始。</h1><p>清晰地安排事情，也给自己留一点余地。</p></div><button class="button primary" data-action="new-task">${ico('plus')}添加任务</button></div><section class="panel"><div class="tabs">${['全部',...statuses].map(s=>`<button data-filter="${s}" class="${taskFilter===s?'selected':''}">${s} <span>${state.tasks.filter(t=>s==='全部'||t.status===s).length}</span></button>`).join('')}</div>${state.tasks.filter(t=>taskFilter==='全部'||t.status===taskFilter).map(taskRow).join('')||'<p class="empty">这个状态下还没有任务。</p>'}</section><section class="execution panel"><div class="section-heading"><h2>交给 AI 的需求 <span>先写清楚，再确认提交</span></h2><button class="button secondary" data-action="new-request">${ico('plus')}起草需求</button></div><div class="notice">${ico('sparkle')}执行器尚未连接。本页仅保存草稿与提交记录，不会实际调用 AI 或运行命令。</div>${state.requests.length?state.requests.map(r=>`<button class="request-row" data-request="${r.id}"><div><strong>${esc(r.title)}</strong><small>${esc(r.body.slice(0,90))}</small></div><span class="queue-status ${r.status}">${queueLabels[r.status]||'未知'}</span><span>↗</span></button>`).join(''):'<div class="request-empty"><span>✧</span><h3>把需求说清楚，是完成的第一步。</h3><p>写下目标、交付物和允许的操作，保存后再确认提交。</p></div>'}</section>`;}
function render(){ $('#app').innerHTML=`${nav()}<div class="main">${header()}<main>${view==='overview'?overview():view==='projects'?projects():view==='knowledge'?knowledge():tasks()}<footer><span>GPT-DOT-WORK · 独立非官方项目</span><span>${storageError?'⚠ 本地保存不可用，请导出备份':'仅当前浏览器保存'} · 虚构演示数据</span></footer></main></div>`;bind();}
function closeModal(){ $('#note-dialog').close();selectedNote=null; }
function modal(content){ const d=$('#note-dialog');d.innerHTML=content;d.showModal(); d.querySelector('[data-close]')?.addEventListener('click',closeModal); d.querySelector('input,textarea,button')?.focus(); }
function noteEditor(id){const n=state.notes.find(n=>n.id===id);selectedNote=id||null;modal(`<form id="note-form"><div class="modal-heading"><div><small>KNOWLEDGE NOTE</small><h2>${n?'编辑笔记':'留下一条新想法'}</h2></div><button type="button" class="close" data-close aria-label="关闭">×</button></div><label>标题<input name="title" required maxlength="120" value="${esc(n?.title)}" placeholder="给想法起个名字"></label><label>所属项目<select name="projectId">${state.projects.map(p=>`<option value="${p.id}" ${p.id===(n?.projectId||selectedProject)?'selected':''}>${p.name}</option>`).join('')}</select></label><label>内容<textarea name="body" required rows="8" maxlength="20000" placeholder="写下想法、背景和下一步…">${esc(n?.body)}</textarea></label><label>标签 <span>用逗号分隔</span><input name="tags" value="${esc(n?.tags?.join(', '))}" maxlength="200" placeholder="知识管理, 灵感"></label><div class="modal-footer"><small>仅保存在当前浏览器，请勿输入敏感信息。</small><button type="submit" class="button primary">保存笔记</button></div></form>`);$('#note-form').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target);let title=f.get('title').trim(),body=f.get('body').trim();if(!title||!body){toast('标题和内容不能为空。');return;}let note={id:n?.id||crypto.randomUUID(),title,body,projectId:f.get('projectId'),tags:f.get('tags').split(/[,，]/).map(s=>s.trim()).filter(Boolean),type:n?.type||'笔记',updated:new Date().toISOString()};if(n)state.notes=state.notes.map(x=>x.id===n.id?note:x);else state.notes.unshift(note);const persisted=save();closeModal();render();if(persisted)toast('笔记已保存到本地');};}
function taskEditor(){modal(`<form id="task-form"><div class="modal-heading"><h2>给下一步一个名字</h2><button class="close" type="button" data-close aria-label="关闭">×</button></div><label>任务名称<input name="title" required maxlength="120" placeholder="一件具体、可以完成的事"></label><label>所属项目<select name="projectId">${state.projects.map(p=>`<option value="${p.id}" ${p.id===selectedProject?'selected':''}>${p.name}</option>`).join('')}</select></label><div class="modal-footer"><small>添加后可以随时调整状态。</small><button type="submit" class="button primary">添加任务</button></div></form>`);$('#task-form').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target),title=f.get('title').trim();if(!title)return;state.tasks.unshift({id:crypto.randomUUID(),title,projectId:f.get('projectId'),status:'待开始',priority:'普通',due:'未设日期'});const persisted=save();closeModal();render();if(persisted)toast('任务已添加');};}
function requestEditor(id){const r=state.requests.find(x=>x.id===id);if(r&&r.status!=='draft'){modal(`<div class="modal-heading"><div><small>EXECUTION REQUEST</small><h2>${esc(r.title)}</h2></div><button class="close" data-close aria-label="关闭">×</button></div><span class="queue-status ${r.status}">${queueLabels[r.status]}</span><p class="request-body">${esc(r.body)}</p><div class="plan-box"><span>结果与日志</span><p>${r.status==='cancelled'?'此本地请求记录已取消。没有启动过任何执行。':'提交记录已保存在本地。执行器未连接，未加入真实队列，也没有运行任何操作。'}</p><small>${esc(r.updated)}</small></div><p class="security-note">未来接入后，涉及外部发送、数据共享、购买或权限变更仍需相应授权。网页或外部文档里的指令不会自动获得权限。</p>${r.status!=='cancelled'?'<button class="button secondary" id="cancel-request">取消此请求</button>':''}`);$('#cancel-request')?.addEventListener('click',()=>{r.status='cancelled';r.updated=new Date().toISOString();const persisted=save();closeModal();render();if(persisted)toast('已取消本地请求记录');});return;}
modal(`<form id="request-form"><div class="modal-heading"><div><small>REQUEST DRAFT</small><h2>${r?'编辑需求草稿':'你希望完成什么？'}</h2></div><button class="close" type="button" data-close aria-label="关闭">×</button></div><label>需求标题<input name="title" required maxlength="120" value="${esc(r?.title)}" placeholder="例如：把公开资料整理成一页摘要"></label><label>目标、交付物与允许的操作<textarea name="body" required rows="7" maxlength="12000" placeholder="我希望…\n交付物是…\n允许的操作…\n需要先问我的事项…">${esc(r?.body)}</textarea></label><div class="notice">当前仅为本地演示。保存草稿不会提交；确认提交也不会触发真实执行。</div><label class="consent"><input type="checkbox" id="request-consent">我确认提交这份需求记录，并知晓执行器未连接。</label><div class="modal-footer"><button class="button secondary" type="submit" name="intent" value="draft">保存草稿</button><button class="button primary" type="submit" name="intent" value="submit">确认提交（演示）</button></div></form>`);$('#request-form').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target),title=f.get('title').trim(),body=f.get('body').trim(),submit=e.submitter.value==='submit';if(!title||!body){toast('请先填写标题和需求。');return;}if(submit&&!$('#request-consent').checked){toast('请先勾选确认，再提交需求记录。');return;}let request={id:r?.id||crypto.randomUUID(),title,body,status:submit?'blocked':'draft',updated:new Date().toISOString()};if(r)state.requests=state.requests.map(x=>x.id===r.id?request:x);else state.requests.unshift(request);const persisted=save();closeModal();render();if(persisted)toast(submit?'提交记录已保存；执行器未连接，未开始执行。':'需求草稿已保存，尚未提交。');};}
function bind(){document.querySelectorAll('[data-project]').forEach(b=>b.onclick=()=>{selectedProject=b.dataset.project;if(view==='projects')render();else location.hash='projects';});document.querySelectorAll('[data-note]').forEach(b=>b.onclick=()=>noteEditor(b.dataset.note));document.querySelectorAll('[data-toggle-task]').forEach(b=>b.onclick=()=>{let t=state.tasks.find(t=>t.id===b.dataset.toggleTask);t.status=t.status==='已完成'?'待开始':'已完成';save();render();});document.querySelectorAll('[data-task-status]').forEach(b=>b.onchange=()=>{state.tasks.find(t=>t.id===b.dataset.taskStatus).status=b.value;save();render();});document.querySelectorAll('[data-decision]').forEach(b=>b.onclick=()=>{state.decisions.find(d=>d.id===b.dataset.decision).resolved=true;save();render();toast('已标记为决定完成');});document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{taskFilter=b.dataset.filter;render();});document.querySelectorAll('[data-request]').forEach(b=>b.onclick=()=>requestEditor(b.dataset.request));document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{let a=b.dataset.action;if(a==='new-note')noteEditor();if(a==='new-task')taskEditor();if(a==='new-request')requestEditor();if(a==='export'){let url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='gpt-dot-work-local-export.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('已生成本地 JSON 导出文件，请妥善保存。');}});$('#knowledge-search')?.addEventListener('input',e=>{query=e.target.value;let pos=e.target.selectionStart;render();$('#knowledge-search').focus();$('#knowledge-search').setSelectionRange(pos,pos);});}
function route(){let next=location.hash.slice(1);view=['overview','projects','knowledge','tasks'].includes(next)?next:'overview';render();}
window.addEventListener('hashchange',route);
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();if(view!=='knowledge'){location.hash='knowledge';setTimeout(()=>$('#knowledge-search')?.focus(),50);}else $('#knowledge-search').focus();}});
route();
